version: "2.3"
services:
    app:
        build: .
        container_name: app
        volumes: 
            - .:/var/www
        networks: 
            - app-network

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports: 
            - "8080:80"
        volumes: 
            - .:/var/www
        networks: 
            - app-network
        
    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks: 
            - app-network

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - app-network

networks:
    app-network:
        driver: bridge